# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            '   Nitin Vinayak Agrawal   '
tagline:          'A Data Science Enthusiast'
description:      ''
url:              http://hyde.getpoole.com
baseurl:          https://nitinvinayak.github.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo
plugins:
  - jekyll-paginate
  - jekyll-include-cache
paginate:         5
gems:
- jekyll-gist
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
